Develop
cristiancastano852/placetogrow pull request #16
Opened 2024-07-01 04:57 UTC by cristiancastano852

Pending for review of barbosa89

2024-07-05 21:39 UTC, barbosa89 requested changes

2024-07-05 21:39 UTC, barbosa89 commented on app/Actions/Microsites/UpdateAction.php
> +        return $microsite;
Agrega espacio antes de cada return

2024-07-05 21:39 UTC, barbosa89 commented on app/Actions/RolePermissions/UpdateRolesAction.php
> +
Eliminar líneas en blanco

2024-07-05 21:39 UTC, barbosa89 commented on app/Actions/User/DeleteAction.php
> +class DeleteAction
Las acciones simples no son requeridas

2024-07-05 21:39 UTC, barbosa89 commented on app/Constants/PermissionSlug.php
> +    public const  CATEGORIES_VIEW_ANY = 'categories.view_any';
Usar enumeraciones

2024-07-05 21:39 UTC, barbosa89 commented on app/Http/Controllers/Auth/AuthenticatedSessionController.php
> +        Log::info('Login page visited');
Eliminar log y cualquier otro que no es requerido

2024-07-05 21:39 UTC, barbosa89 commented on resources/views/admin/rolePermission/index.blade.php
> +                <h1 class="text-xl text-gray-800 leading-tight">Gestión de usuarios</h1>
Esta vista debería ser de usuarios

2024-07-05 21:39 UTC, barbosa89 commented on tests/Feature/Microsites/MicrositesDestroyTest.php
> +        $this->withoutExceptionHandling();
Este método no se debe usar

2024-07-19 05:36 UTC, cristiancastano852 commented
@barbosa89 Cambios aplicados

2024-07-30 20:57 UTC, barbosa89 approved these changes

2024-07-30 20:57 UTC, merged